### PR TITLE
Add placement in profile landing page

### LINKED ISSUE #187: Add placement in profile landing page
Users have been requesting to see what 'place' they are on bluesky, some have also believed that they could get this info on clearsky already. This is now in place:

API: /api/v1/anon/placement/<client_identifier>

returns {"identity": string, "status": bool, "data": int || null}

Placement idea/guide:

desktop:
image

mobile:
image

### PR DESCRIPTION
**Pull request by seanmunson**
Fixes #187
image

- [x] Fetched placement data /api/v1/anon/placement/<client_identifier>
- [x] Display value
- [x] If blank, display nothing
- [x] If username unconfigured, but placement data returns, still display placement
- [x] Update CSS as necessary
- [x] Test successful on specified user accounts
- [x] Use locale-based string conversion.

### CODE REVIEW

**Comment by thieflord06** [comment]
@seanmunson checks failed.

**Comment by thieflord06** [comment]
test handles in staging:

bmann.ca
expede.wtf
crage.bsky.social
sarah.bsky.social
ian.bsky.social
fmcruz.bsky.social
michael.bsky.social
matthew.bsky.social
forrest.bsky.social
geoah.me
travis.bsky.social
herbie.bsky.social
tay.bsky.social
mainedeb.bsky.social

**Comment by thieflord06** [comment]
adding placements in progress.

**Comment by thieflord06** [comment]
There should be enough placements added to test this.

**Comment by seanmunson** [comment]
> There should be enough placements added to test this.

Lots of crappy accounts there, 

updated the handle display to communicate when the handle is unconfigured, because that was blocking out the placement count. Now looks like : 

image

Open to suggestions for improvements of this fix.

Merry Christmas!

**Comment by thieflord06** [comment]
I'm confused, because there is a return for the placement but it also says unconfigured. 


I think maybe a ? If there isn't a placement. I also think that it might be ok if nothing is there, since:

There hasn't been anything there before.
It's at the end of a line, so it doesn't look weird if nothing is there anyway.

**Comment by thieflord06** [comment]
What is returning unconfigured?

**Comment by thieflord06** [comment]
From my brief research, this may be from accounts that are no longer active. and if they return a placement, it hasn't been marked inactive in the db yet.

**Comment by thieflord06** [comment]
Ahh I see, the unconfigured is in place of the hyperlink to the profile. I think we may need to work thru what the UX for that is @noahm 

I couldn't find the profile in the app in the example (jay.bsky.social) so I think that NOT displaying the hyperlink is the way to go because it won't take you anywhere.

**Comment by seanmunson** [comment]
> Ahh I see, the unconfigured is in place of the hyperlink to the profile. I think we may need to work thru what the UX for that is @noahm
> 
> I couldn't find the profile in the app in the example (jay.bsky.social) so I think that NOT displaying the hyperlink is the way to go because it won't take you anywhere anyway.

This is the resolved.data returned data: 

image

Maybe determine graceful fallback is another ticket?

**Comment by thieflord06** [comment]
I agree. I'll make a separate ticket. I think everything is addressed for this at this point.

**Comment by thieflord06** [comment]
Oh wait, what about number formatting? 

65888 vs 65,888

**Comment by seanmunson** [comment]
> Oh wait, what about number formatting? 
> 
> 65888 vs 65,888

No commas. 

Do we want them locale formatted?

**Comment by thieflord06** [comment]
Yes.

**Comment by seanmunson** [comment]
> Yes.

done
image

**Review by noahm — APPROVED** [review]

**Review by thieflord06 — APPROVED** [review]

**Pull request merged**
