### PR TITLE
Big bundle optimization changes

### LINKED ISSUE #171: Optimize JS/CSS bundle size
We're currently shipping a 7.3mb JS bundle and 4.9mb of CSS. That's an awful lot!

We need be more mindful of this, removing unnecessary bloat, minifying, and doing bundle splitting to reduce the initial load times.

### PR DESCRIPTION
**Pull request by noahm**
This is a pretty big change to our build system, but I think the benefits are probably worth it.

Preview at: https://vite-builds.clearskyui.pages.dev/

Primarily it does two things:
1. replaces `esbuild` with `vite` for bundling/building (esbuild is still used under the hood)
    - annoyingly, this forces a bunch of changes like renaming `.js` extensions to `.jsx` wherever jsx syntax is used
    - but it also provides many little developer conveniences like HMR (hot module replacement, no need to refresh your browser page after saving changes to a component, they just re-render inline with your changes, preserving their local component state)
2. adds a `React.lazy` wrapper around a few components in strategic places to create a separate js/css chunk so we can defer loading some of the app code

The net result of this is instead of one extremely large JS/CSS bundle (over 10mb before compression) with very little optimization techniques the build output is a lot of smaller files that will only be loaded on demand, depending on which page/tab is being used in any given moment. (only the home stats table itself is larger than 1mb, thanks to ag-grid)

This will probably have a hugely beneficial effect for mobile users on slower and less reliable cellular networks, as the home page now loads with only 1mb JS/CSS combined payload (288kb after compression). I expect this can be reduced considerably further by focusing on the contents of the `use-resolve-account-*` bundle.

There's a few things that I need to check on before I'd consider this ready to go:

- [x] several of the other standalone html files aren't going to have the logo image show up correctly. I think this is an easy fix, but need to look closer later on
- [x] some CSS isn't being applied correctly (the inline html template pointed out in comment below, plus in the popout tooltip when hovering over accounts)
- [x] re-enable sourcemaps output

Closes #171 

The entire build output from this PR:
image

### CODE REVIEW

**Comment by thieflord06** [comment]
This artifact briefly shows before the page loads, we discussed it before and I think it was fixed in #161 
image

**Comment by noahm** [comment]
Ah that's the blurred out placeholder layout that starts on the page before React finishes its first render. It must be missing a few something after my changes here that has alerted its appearance to this less recognizable form.

**Comment by noahm** [comment]
I think this is ready for a more thorough review now!

**Comment by thieflord06** [comment]
Let's check it out!

**Comment by thieflord06** [comment]
Functional tests seem to be checking out.

**Comment by thieflord06** [comment]
It seems like some of the PDS icons are missing.

image

**Comment by noahm** [comment]
Those aren't supposed to be a PDS icon, but just a favicon lookup for a given domain name used as a handle. These in particular are served through https://icon.horse/ and it seems that they failed to serve a response in this case. Viewing the same page myself it seems to resolve an image correctly, so possibly a temporary outage on their part? Or are we running up against request limits they impose? (are we paying for a paid plan with them?)

**Comment by thieflord06** [comment]
Ah, no, we don't have a subscription to this. There must be rate limiting going on. Would it be better to cache these icons ourselves?

**Comment by noahm** [comment]
No, I looked into it a bit and I think that's way more trouble than it's worth. We can keep an eye out for how often they fail, but for now it's still the easiest solution, and for a very unimportant part of the app

**Comment by thieflord06** [comment]
I agree.

**Comment by noahm** [comment]
Oh, I should also be clear that this PR does not change how we use those icons, and i'm confident any issues with them you see here will also be present in production.

**Comment by thieflord06** [comment]
Right, right. I think I've done all the testing against it that I can. 

Do you think it's good to go?

**Review by thieflord06 — APPROVED** [review]
Passed functional checks for me.

**Comment by noahm** [comment]
Yup, i think it's good to go!

**Pull request merged**
