### PR TITLE
🛠️Fix : Tooltip for a user has outsized large DID

### LINKED ISSUE #173: Tooltip for a user has outsized large DID
**Describe the bug**
Tooltip can be helpful to avoid jumping through navigation.

But one of its downsides is the wild huge DID

image

**To Reproduce**
Mouse over any user.

**Expected behavior**
Show did in small font comparable to the bio.

### PR DESCRIPTION
**Pull request by akash70629**
# Description 
did added in a small font.

## Fixes #173 

# Screenshot 

## Before 
image

## After 
image

### CODE REVIEW

**Comment by akash70629** [comment]
@noahm Please review and merge this PR.

**Comment by noahm** [comment]
@akash70629 I don't think slightly decreasing the font size on this really addresses the underlying issue. Even at the smaller size the DID still isn't visible in full, cut off by the edge of the card (illustrated in pink), and the layout is generally awkward with the DID appearing larger than the handle, yet indented to appear after the handle. 

Can you instead try to have the DID display on its own line below the handle, and in the same font size as the handle? (illustrated in blue)

image

**Comment by thieflord06** [comment]
@akash70629 Any progress on this?

**Comment by noahm** [comment]
superseded by #226

**Pull request closed without merging**
