### PR TITLE
Fix handle-history

### LINKED ISSUE #111: requests sending handle in did format
ex: /api/v1/anon/get-handle-history/did:plc:janelleleigh.bsky.social

It looks to be only limited to this endpoint

### PR DESCRIPTION
**Pull request by gnmerritt**
Same as #116 except against `dev` instead of `main`

Closes #111

### CODE REVIEW

**Comment by thieflord06** [comment]
Is this ready?

**Comment by gnmerritt** [comment]
hey @thieflord06 this was ready to go, any reason it didn't get merged?

**Comment by thieflord06** [comment]
It must have gotten closed out when I moved the repo.

**Comment by thieflord06** [comment]
It must have gotten closed out when I moved the repo.

**Comment by gnmerritt** [comment]
ok np I'll repost

**Pull request closed without merging**
